version: '2'
services:
  splunk:
    hostname: splunk
    image: ronniedada/docker-stats-splunk:latest
    environment:
      SPLUNK_START_ARGS: --accept-license
    volumes:
      - /opt/splunk/etc:/opt/splunk/etc
      - /opt/splunk/var:/opt/splunk/var
    ports:
      - "9997:9997"
      - "8089:8089"
      - "8000:8000"
      - "8088:8088"
